/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    Content: typeof import('./pages/dashboard/components/Content.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    FooterContent: typeof import('./components/FooterContent.vue')['default']
    ItemCard: typeof import('./pages/dashboard/components/ItemCard.vue')['default']
    Language: typeof import('./components/Language.vue')['default']
    MainTitle: typeof import('./pages/dashboard/components/MainTitle.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
  }
}
