const { build } = require('../mini-webpack')
const assert = require('assert')
const path = require('path')
const fs = require('fs')
const entry = path.resolve(__dirname, './src/index.js')
const output = path.resolve(__dirname, './dist/index.js')
build(entry, output)
assert.match(fs.readFileSync(output, 'utf-8'), /absRequire, exports, graph\[file\].code/)
console.log('Passed!')